"""create replys table

Revision ID: a31e8cc569bc
Revises: c5f782365bf0
Create Date: 2021-12-27 14:54:26.160041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31e8cc569bc'
down_revision = 'c5f782365bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replys', 
    sa.Column('id',sa.Integer(),nullable=False,primary_key=True),
    sa.Column('content', sa.String(),nullable=False),
    sa.Column('owner_id',sa.Integer(),nullable=False),
    sa.Column('comment_id',sa.Integer(),nullable=False),
    sa.Column('created_at',sa.TIMESTAMP(timezone=True),nullable=False,server_default=sa.text('NOW()')),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replys')
    # ### end Alembic commands ###
