"""create comments table

Revision ID: cdbb75360a69
Revises: 4643bf18e22f
Create Date: 2021-12-22 17:20:05.252011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbb75360a69'
down_revision = '4643bf18e22f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments', 
    sa.Column('id',sa.Integer(),nullable=False,primary_key=True),
    sa.Column('content', sa.String(),nullable=False),
    sa.Column('owner_id',sa.Integer(),nullable=False),
    sa.Column('post_id',sa.Integer(),nullable=False),
    sa.Column('created_at',sa.TIMESTAMP(timezone=True),nullable=False,server_default=sa.text('NOW()')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
